steps:

# Build images
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/quortex-registry/dvbsub2ttml:rel-$TAG_NAME','-f','./Dockerfile', './service/dvbsub2ttml/']


timeout: 3600s

options:
  machineType: 'E2_HIGHCPU_8'

images:
- 'eu.gcr.io/quortex-registry/dvbsub2ttml/service/lbalancer:rel-$TAG_NAME'
